### ISSUE TITLE
Allow -r dotenv-flow/config

### ISSUE THREAD

**Issue by krzkaczor** [kerimdzhanov/dotenv-flow#11]
I prefer do leave .env loading totally up to the user of the app so I don't have anywhere in my code `require('dotenv').config();` but rather I use `node -r dotenv/config app.js` And if it runs in docker then docker takes care of injecting it and I dont have to change anything in my app code.

Unfortunatelly this doesn't work with this lib :(

**Comment by kerimdzhanov** [comment]
Hi @krzkaczor,
I understand what you mean and I will try to find time to implement this feature.
Or, I would be very glad if you send me a PR.

**Comment by jlandrum** [comment]
Created a pull request with basic support.
https://github.com/kerimdzhanov/dotenv-flow/pull/12

**Comment by kerimdzhanov** [comment]
First of all, thank you guys for your support in developing of this library!

I've just published a new release candidate ([`v0.4.0.-rc.1`](https://www.npmjs.com/package/dotenv-flow/v/0.4.0-rc.1)) with this feature support adding the ability to configure `-r dotenv-flow/config` via environment variables and/or command line switches.

You can now install it and give a try.

Please, let me know if something goes wrong. Otherwise I will release `v0.4.0` in a few days.
