### ISSUE TITLE
default_node_env not setting NODE_ENV

### ISSUE THREAD

**Issue by kzima** [kerimdzhanov/dotenv-flow#13]
When using 'default_node_env' v0.4 dotenv-flow in Windows with node v11.4.0, the default config option as it is not setting a NODE_ENV. 

Downgraded to v0.1 and it works again.

**Comment by kerimdzhanov** [comment]
Hi @kzima,

Yes, and I believe that it's correct logic, and that's why:

Since we introduced the [`node_env`](https://github.com/kerimdzhanov/dotenv-flow#optionsnode_env) option (in [v0.2.0](https://github.com/kerimdzhanov/dotenv-flow/blob/master/CHANGELOG.md#020-2018-12-23)), we gave developers the ability to be independent from `process.env.NODE_ENV` at all, but read its value by default if the `node_env` is not set. While implementing this, I realized that we shouldn't set `process.env.NODE_ENV` from within the module because in some cases it can be used for totally different things and it's all up to developers how they manage their process' environment.

So, regarding your case, it seems that you depend on `dotenv-flow` to setup your `process.env.NODE_ENV` to a default value (hopefully it's `development`), but you actually shouldn't.

I recommend you to set your `process.env.NODE_ENV` by yourself, because it is more obvious, especially if you are using it directly within your own code.

You need to have something like this:

```js
process.env.NODE_ENV || (process.env.NODE_ENV = 'development'); // or process.env.NODE_ENV = process.env.NODE_ENV || 'development';

// then just
require('dotenv-flow').config(); // without any options, it uses `process.env.NODE_ENV` by default
```

**Comment by Polatrite** [comment]
The documentation needs to be updated for this value, because it's misleading developers.

https://github.com/kerimdzhanov/dotenv-flow#environment-variables
https://github.com/kerimdzhanov/dotenv-flow#optionsdefault_node_env

**Comment by kerimdzhanov** [comment]
Hi @Polatrite,

Could you please give more details, what exactly misleads you?
