### ISSUE TITLE
.env is not working as aspected

### ISSUE THREAD

**Issue by viveksharmaui** [kerimdzhanov/dotenv-flow#18]
hi guy's i have 3 different env file 

1) .env (this set up development and production env)
2) .env.development (this contain all development configuration)
3) .env,production (this contains all production configuration)

When i start node js it was unable to get NODE_ENV from .env file but working fine with dotenv with dotenv-flow , and i use dotenv with dotenv-flow .
Then dotenv-flow returns this warning 
`dotenv-flow: "NODE_ENV" is already defined in `process.env` and will not be overwritten`
but when i only use dotenv-flow it was unable to get NODE_ENV from .env 

```
 // This module is responsible for adding env variable from .env file

// Importing 3rd Party Module

import dotEnv from "dotenv";

import dotEnvFlow from "dotenv-flow";

// Dot Env will get all variable's from .env file
dotEnv.config();
dotEnvFlow.config();

// Export Dot Env Module
export { dotEnv , dotEnvFlow };
```

**Comment by kerimdzhanov** [comment]
Hi @viveksharmaui,

You don't need to have the original `dotenv` package, because it's already a dependency of `dotenv-flow`.

The following just should work fine:

```js
import dotenvFlow from 'dotenv-flow';

dotenvFlow.config();
```

Also, note that exporting the `dotenvFlow` is redundant, because when you call `.config()` it fills out `process.env` which is global.

As for the `NODE_ENV` environment variable, it shouldn't be placed in any `.env` file. This environment variable controls which of the `.env` file will be loaded.

For example, if you run your script like:
```sh
$ NODE_ENV=production node your_script.js
```
it will load environment variables from `.env` (the default) and `.env.production` (node_env-specific).

If you run your script like:
```sh
$ NODE_ENV=development node your_script.js
```
it will load environment variables from `.env` and `.env.development`.

But if you run your script without specifying `NODE_ENV`, like:
```sh
$ node your_script.js
```
it will only load the `.env` file (the default one).

**Comment by viveksharmaui** [comment]
Thank you so much for helping me
