### ISSUE TITLE
Specifying NODE_ENV in .env.local file 

### ISSUE THREAD

**Issue by welljsjs** [kerimdzhanov/dotenv-flow#27]
It's currently possible to set NODE_ENV by passing the `--node-env` option or by using `cross-env`. 

However, it's not possible to set NODE_ENV in a `.env` file. 

Example: 

*.env.local*
```sh
NODE_ENV=development
```

*.env.development.local*
```sh
[development variables...]
```

This would be really helpful in cases where we can't hardcode the node environment or just want to run npm start and load the specific environment file depending on another `.env` file. 

```js
scripts: {
    "start": "node index.js"    // <-- instead of having start-dev, start-prod etc. one could just run the start script and specify the node environment in a .env file
}
```

Of course this would only work if NODE_ENV is read from files with lower priorities, i.e. `.env` and `.env.local`.

**Comment by kerimdzhanov** [comment]
Hi @welljsjs,

It's actually not a good idea to configure `NODE_ENV` in `.env*` files,
because it controls which of `.env*` files will be loaded.

I recommend you to set your default node environment before `require`'ing "dotenv-flow", like this:
```js
process.env.NODE_ENV = process.env.NODE_ENV || 'development';

require('dotenv-flow').config();

// ...
```

Or specify it directly in your `package.json` scripts, like:

```json
"scripts": {
  "start":      "NODE_ENV=development node index.js",
  "test":       "NODE_ENV=test mocha test/*.spec.js",
  "start:prod": "NODE_ENV=production node index.js"
}
```

It is a good practice that used in the vast majority of projects I've seen.

**Comment by welljsjs** [comment]
Thanks for your response. 

Let me start at the bottom...

> Or specify it directly in your package.json scripts, like:

That's what I'm trying to prevent - I'd prefer to have a single "start" command.

> It's actually not a good idea to configure NODE_ENV in .env* files,
because it controls which of .env* files will be loaded.

Is that the case? 

So say I put "NODE_ENV=development" in `.env.local`, does that then load `.env.development.local`?  That's exactly what I'm trying to achieve but I believe it doesn't. Or did I get you wrong here? 

Let me give you another example: 

I've got `.env.local` and `.env.development.local` in my local repository (we don't put `*.local*` files on the remote, obviously).

`.env.local` sets NODE_ENV to whatever environment I want to run the application in (let's say "development" for this example).

Does dotenv-flow pick that up? I.e. does it load `.env.development.local` in that case? It doesn't for me. 

I think that would make things easier since we wouldn't need n start scripts for n environments and we could just change NODE_ENV in .env.local to the environment we want to run. 

Not sure if we were talking about the same thing.

**Comment by kerimdzhanov** [comment]
You're right about that it doesn't load and parse `.env.local` before considering what to load next.

And yeah, I understand what you mean, but I'm not sure that it's really easier/better to open, edit, then save the `.env.local` file instead of just running a different script like `npm start:prod`.

Consider that you as well as other developers in your team could find `start`, `start:prod`, and `test` commands in your `package.json`'s `"scripts"` section. It's under version control and doesn't need any clarifications. Otherwise, you'll need to describe this behavior somewhere in your project's README or developer's guide because, as for me, it doesn't look obvious.

Also, this feature may add some misunderstandings into the library, like _What should the library do if `NODE_ENV` is configured in the `.env` file?_ Ignore it and/or show warnings? We will have to argue why it doesn't work and why it's not a good idea.

If you have any arguments on this, please let me know. I'm not against new features, but it should be really useful and obvious as much as possible. Maybe you have more use cases? Or another way to make it more obvious?
