### ISSUE TITLE
no error property set when .env file is not present

### ISSUE THREAD

**Issue by vineetdigit** [kerimdzhanov/dotenv-flow#41]
Upon calling .config(), dotenv sets an error property in the returned object when .env is not present. 

```
var result = require("dotenv").config();

// result.error property is set when .env is not present in the root directory of the node project
```

dotenv-flow does not set an error property, and instead it only has an empty "parsed" object.

```
var result = require("dotenv-flow).config();

// restult.error is not present, but result.parsed is an empty object
```
It would be nice to have a consistent behavior as "dotenv"

**Comment by kerimdzhanov** [comment]
Hey @vineetdigit,

The reason for such difference in behavior is that in "dotenv-flow", we may not have `.env` file (while having i.e. `.env.development`, `.env.production`, etc.,), so we can't consider it as an error.

On the other hand, if we have no `.env*` files at all, this behavior might be reasonable.

What are your thoughts?

**Comment by vineetdigit** [comment]
My exact thoughts. As long as at least one of the files is present and it was successfully parsed, then result.parsed property will contain parsed values and result.error property should be undefined. Otherwise, result.error property will be set but the result.parsed will be undefined.

**Comment by kerimdzhanov** [comment]
Hi @vineetdigit,

Since "dotenv-flow" supports multiple files loading at the same time, I am thinking about changing the signature of the `result.errors` object to per-file grouped errors.

For example, if one of the ".env*" files is missing (let's suppose `.env.development` while we're running with `NODE_ENV=development`), calling `require('dotenv-flow').config()` should result in something like:

```js
{
  "parsed": { /* ... */ },
  "errors": {
    ".env.development": "/path/to/project/.env.development file is not present"
  }
}
```

Apart from the missing files, there might be other parsing-related errors, so hopefully, that would make sense what exact file raises an error.

As for the exact missing files, it might be totally fine to not have all the files present while using "dotenv-flow" in a project. For example, `.env.default`, `.env.local`, `.env.development.local`, etc. in the majority of cases will not be present. So, we might need to have some additional logic and/or configuration options on which missing files should be considered as an error.

**Comment by kerimdzhanov** [comment]
I see. Thanks for your thoughts and the idea in general!
