### ISSUE TITLE
Error with symlink  .env.local

### ISSUE THREAD

**Issue by filoucrackeur** [kerimdzhanov/dotenv-flow#46]
Hello 
it seems that file which are symlinks are not found and not loaded :( 

```bash
$ ls -la
.env OK
.env.local -> /var/xxx/xxx/.env.local   NOK

```

**Comment by kerimdzhanov** [comment]
It seems that this behavior is not relevant since Node.js v10, where `fs.readFile` started reading the symlink target files (not the content of the symlink file itself), and since _dotenv-flow_ utilizes `fs.readFileSync` to read the contents of the `.env*` files, if you upgrade Node.js, _dotenv-flow_ will be reading symlinks as well.
