### ISSUE TITLE
Is DOTENV_FLOW_SILENT supposed to suppress "already defined" messages?

### ISSUE THREAD

**Issue by Asuza** [kerimdzhanov/dotenv-flow#52]
I've tried a few different ways to silence these types of messages:
```
dotenv-flow: "DATABASE_HOST" is already defined in `process.env` and will not be overwritten
dotenv-flow: "DATABASE_PORT" is already defined in `process.env` and will not be overwritten
dotenv-flow: "DATABASE_NAME" is already defined in `process.env` and will not be overwritten
dotenv-flow: "DATABASE_USERNAME" is already defined in `process.env` and will not be overwritten
dotenv-flow: "DATABASE_PASSWORD" is already defined in `process.env` and will not be overwritten
```
Because I use `dotenv-flow` in several files, these messages get repeated many times.

I've tried setting `DOTENV_FLOW_SILENT` in my environment via PowerShell, and confirmed that it is indeed there. The documentation isn't clear on what the value is supposed to be, so I've set it to "silent" based on skimming the code.

```powershell
PS C:\dev\myproject> Get-ChildItem Env:DOTENV_FLOW_SILENT

Name                           Value
----                           -----
DOTENV_FLOW_SILENT             silent
```

Adding the environment variable to my _.env_ file also does not seem to do anything.

I am using version 3.2.0.

Am I doing something wrong with this setting?

**Comment by kerimdzhanov** [comment]
Hei @Asuza,

Sorry for disappearing 😅.

So yeah, you just need to make sure that `require('dotenv-flow').config();` is specified at least once in your Node.js process. You don't need to check for environment variables before requiring it. By Node.js's design, I'd recommend the following:

1. Somhere in your project create a file, for example `lib/dotenv-flow.js`, with the following initialization code:
```js
require('dotenv-flow').config();
```
That's it (one-liner).

2. From the other files within your project, you can just require your `lib/dotenv-flow.js` to make sure that it's loaded and initialized. As easy as follows:

```js
require('./lib/dotenv-flow');
```

Node.js will not re-initialize the file again if it has already been done by the other "require" instruction before. So, you can make sure that the file is loaded and initialized without any unnecessary warnings or pre-checks.

**Comment by Asuza** [comment]
Thank you for the response, @kerimdzhanov! I'm hoping to give your latest suggestion a try. No worries at all about the delay.

**Comment by merlox** [comment]
I personally think it's a terrible design decision. Most other dotenv libraries simply allow you to specify require('dotenv...') in every file that needs to access those variables. Nobody is tryint to "override" process.env variables.

I suggest you to make the functionality identical to all other dotenv libraries to avoid confusion because it took me a while to figure the right way to import this since I have multiple entry files.

**Comment by kerimdzhanov** [comment]
Hi @merlox,

Thanks for the suggestion and a bit of criticism 😜

With regards to "require in every file", it is totally fine but the problem is in `.config()` every time we "require", since it assigns `process.env` which is shared within the node's process (so, it's kinda designed to be the same as dotenv).

Above, I am just suggesting having a shared (single point of configuration) file basically for your own `.config()` call in case if you'd like to have some custom configuration for dotenv-flow. And, btw, if you're okay with all the default options, you could just do `require('dotenv-flow/config');` in every file where you need to access `process.env.*`, and there won't be any warnings and redundant fs hits.

As for the "is already defined" warning, it's actually made for another purpose, Now I realize that the message is not very clear, thanks for mentioning it 👍.

I am thinking of better documentation for dotenv in general. We have a lot of different use cases and "best practices", so I just need a bit more time to create a wiki and totally rework the README 😅
